package com.ventanas;

import com.clases.divisa.PesoMexicano;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.math.BigDecimal;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author mcore
 */
public final class Conversor extends javax.swing.JFrame {

    int xMouse;
    int yMouse;
    PesoMexicano pesoMexicano = new PesoMexicano();
    String valorDivisa;
    String valorSeleccionTipoDivisa;
    String infoConversionRealizada;
    String resultadoConversion;

    /**
     * Creates new form MenuConversion
     */
    public Conversor() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        ventanaIngresoDivisa.setBackground(new Color(0, 0, 0, 0));
        btnMinimizarVentana.setBackground(new Color(0, 0, 0, 0));
        mostrarVentanaBienvenida();
        ocultarVentanaIngresoDivisa();
        ocultarPanelValorDivisa();
        ocultarPanelSeleccionDivisa();
    }

    public void ocultarVentanaBienvenida() {
        ventanaBienvenida.setVisible(false);
    }

    public void ocultarVentanaIngresoDivisa() {
        ventanaIngresoDivisa.setVisible(false);
    }

    public void mostrarVentanaBienvenida() {
        ventanaBienvenida.setVisible(true);
    }

    public void mostrarVentanaIngresoDivisa() {
        ventanaIngresoDivisa.setVisible(true);
    }

    public void ocultarPanelValorDivisa() {
        panelValorDivisa.setVisible(false);
        campoIngresoDivisa.setVisible(false);
        instruccionCampoIngresoDivisa.setVisible(false);
        btnIngresoDivisa.setVisible(false);
    }

    public void ocultarPanelSeleccionDivisa() {
        panelSeleccionDivisa.setVisible(false);
        instruccionSeleccionDivisa.setVisible(false);
        campoSeleccionDivisa.setVisible(false);
        btnSeleccionDivisa.setVisible(false);
    }

    public void ocultarPanelResultadosDivisa() {
        panelResultadosDivisa.setVisible(false);
        resultadoDivisa.setVisible(false);
        btnOtraConversion.setVisible(false);
    }

    public void mostrarPanelValorDivisa() {
        panelValorDivisa.setVisible(true);
        campoIngresoDivisa.setVisible(true);
        instruccionCampoIngresoDivisa.setVisible(true);
        btnIngresoDivisa.setVisible(true);
    }

    public void mostrarPanelSeleccionDivisa() {
        panelSeleccionDivisa.setVisible(true);
        instruccionSeleccionDivisa.setVisible(true);
        campoSeleccionDivisa.setVisible(true);
        btnSeleccionDivisa.setVisible(true);
    }

    public void mostrarPanelResultadosDivisa() {
        panelResultadosDivisa.setVisible(true);
        resultadoDivisa.setVisible(true);
        btnOtraConversion.setVisible(true);
    }

    public boolean esMayorQueCero(String valorUsuario) {
        double valorToDouble = Double.valueOf(valorUsuario);
        return valorToDouble > 0;
    }

    public void mostrarResultadosDivisa(double valorUsuarioToDouble) {
        infoConversionUno.setText("El ajuste de $ " + valorUsuarioToDouble);
        infoConversionDos.setText(valorSeleccionTipoDivisa + " es de: ");
        resultadoDivisa.setText(String.valueOf(resultadoConversion));
    }
    
    public void reestablecerValoresDivisa() {
        campoIngresoDivisa.setText("");
        campoSeleccionDivisa.setSelectedItem("Peso Mexicano (MXN) a Dólar Américano (USD)");
        infoConversionUno.setText("");
        infoConversionDos.setText("");
        resultadoDivisa.setText("");
    }

    /**
     * PAra logo de escritorio, etc.
     *
     * @Override public Image getIconImage() { Image retImage =
     * Toolkit.getDefaultToolkit().
     * getImage(ClassLoader.getSystemResource(name)); }
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        menuConversiones = new FondoPanelMenu();
        btnCerrarVentana = new javax.swing.JLabel();
        btnMinimizarVentana = new javax.swing.JLabel();
        btnConversionMoneda = new javax.swing.JLabel();
        btnConversionTemperatura = new javax.swing.JLabel();
        btnBienvenida = new javax.swing.JLabel();
        ventanaBienvenida = new FondoBienvenida();
        tituloBienvenida = new javax.swing.JLabel();
        nombreDesarrollador = new javax.swing.JLabel();
        ventanaIngresoDivisa = new javax.swing.JPanel();
        panelValorDivisa = new FondoPanelesPequenos();
        instruccionCampoIngresoDivisa = new javax.swing.JLabel();
        campoIngresoDivisa = new javax.swing.JTextField();
        btnIngresoDivisa = new javax.swing.JButton();
        panelSeleccionDivisa = new FondoPanelesPequenos();
        instruccionSeleccionDivisa = new javax.swing.JLabel();
        campoSeleccionDivisa = new javax.swing.JComboBox<>();
        btnSeleccionDivisa = new javax.swing.JLabel();
        panelResultadosDivisa = new FondoPanelesPequenos();
        resultadoDivisa = new javax.swing.JLabel();
        btnOtraConversion = new javax.swing.JLabel();
        infoConversionUno = new javax.swing.JLabel();
        infoConversionDos = new javax.swing.JLabel();
        FondoPrincipal = new JLabelTransparente();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuConversiones.setBackground(new java.awt.Color(0, 102, 153));
        menuConversiones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrarVentana.setBackground(new java.awt.Color(255, 0, 0));
        btnCerrarVentana.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCerrarVentana.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarVentana.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCerrarVentana.setText("x");
        btnCerrarVentana.setOpaque(true);
        menuConversiones.add(btnCerrarVentana, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 30));

        btnMinimizarVentana.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnMinimizarVentana.setForeground(new java.awt.Color(255, 255, 255));
        btnMinimizarVentana.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMinimizarVentana.setText("_");
        btnMinimizarVentana.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnMinimizarVentana.setOpaque(true);
        menuConversiones.add(btnMinimizarVentana, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 30));

        btnConversionMoneda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnConversionMoneda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnConversionMoneda.setText("Conversor de Moneda");
        btnConversionMoneda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnConversionMoneda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConversionMoneda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConversionMonedaMouseClicked(evt);
            }
        });
        menuConversiones.add(btnConversionMoneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 220, 30));

        btnConversionTemperatura.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnConversionTemperatura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnConversionTemperatura.setText("Conversor de Temperatura");
        btnConversionTemperatura.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnConversionTemperatura.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConversionTemperatura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConversionTemperaturaMouseClicked(evt);
            }
        });
        menuConversiones.add(btnConversionTemperatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 220, 30));

        btnBienvenida.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBienvenida.setText("Bienvenida");
        btnBienvenida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnBienvenida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBienvenida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBienvenidaMouseClicked(evt);
            }
        });
        menuConversiones.add(btnBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 220, 30));

        getContentPane().add(menuConversiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 470));

        ventanaBienvenida.setBackground(new java.awt.Color(102, 255, 102));
        ventanaBienvenida.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloBienvenida.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tituloBienvenida.setForeground(new java.awt.Color(0, 0, 0));
        tituloBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloBienvenida.setText("Bienvenido(a)");
        ventanaBienvenida.add(tituloBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 620, -1));

        nombreDesarrollador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nombreDesarrollador.setForeground(new java.awt.Color(0, 0, 0));
        nombreDesarrollador.setText("Desarrollado por: Eduardo Reyes Hernández");
        ventanaBienvenida.add(nombreDesarrollador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 340, -1));

        getContentPane().add(ventanaBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 630, 470));

        ventanaIngresoDivisa.setBackground(new java.awt.Color(0, 204, 204));
        ventanaIngresoDivisa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelValorDivisa.setBackground(new java.awt.Color(153, 0, 153));
        panelValorDivisa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        instruccionCampoIngresoDivisa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        instruccionCampoIngresoDivisa.setForeground(new java.awt.Color(0, 0, 0));
        instruccionCampoIngresoDivisa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        instruccionCampoIngresoDivisa.setText("Ingresa la cantidad de dinero que deseas convertir:");
        panelValorDivisa.add(instruccionCampoIngresoDivisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 580, 30));

        campoIngresoDivisa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoIngresoDivisa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoIngresoDivisa.setBorder(null);
        campoIngresoDivisa.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        campoIngresoDivisa.setMaximumSize(new java.awt.Dimension(2, 2));
        campoIngresoDivisa.setNextFocusableComponent(btnIngresoDivisa);
        campoIngresoDivisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoIngresoDivisaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoIngresoDivisaKeyTyped(evt);
            }
        });
        panelValorDivisa.add(campoIngresoDivisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 240, 40));

        btnIngresoDivisa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnIngresoDivisa.setText("Ingresar Valor");
        btnIngresoDivisa.setAlignmentX(0.5F);
        btnIngresoDivisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIngresoDivisaMouseClicked(evt);
            }
        });
        panelValorDivisa.add(btnIngresoDivisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, -1, -1));

        ventanaIngresoDivisa.add(panelValorDivisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 580, 430));

        panelSeleccionDivisa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        instruccionSeleccionDivisa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        instruccionSeleccionDivisa.setForeground(new java.awt.Color(0, 0, 0));
        instruccionSeleccionDivisa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        instruccionSeleccionDivisa.setText("Selecciona la moneda a la que deseas convertir tu dinero:");
        panelSeleccionDivisa.add(instruccionSeleccionDivisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 580, 30));

        campoSeleccionDivisa.setBackground(new java.awt.Color(70, 174, 124));
        campoSeleccionDivisa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoSeleccionDivisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Peso Mexicano (MXN) a Dólar Américano (USD)", "Peso Mexicano (MXN) a Euro (EUR)", "Peso Mexicano (MXN) a Libra Esterlina (GBP)", "Peso Mexicano (MXN) a Yen (JPY)", "Peso Mexicano (MXN) a Won Coreano (KRW)", "Dólar Americano (USD) a Peso Mexicano (MXN)", "Euro (EUR) a Peso Mexicano (MXN)", "Libra Exterlina (GBP) a Peso Mexicano (MXN)", "Yen (JPY) a Peso Mexicano (MXN)", "Won Coreano (KRW) a Peso Mexicano (MXN)" }));
        panelSeleccionDivisa.add(campoSeleccionDivisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 310, 40));

        btnSeleccionDivisa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSeleccionDivisa.setText("Ingresa el Valor");
        btnSeleccionDivisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSeleccionDivisaMouseClicked(evt);
            }
        });
        panelSeleccionDivisa.add(btnSeleccionDivisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 140, 31));

        ventanaIngresoDivisa.add(panelSeleccionDivisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 580, 430));

        panelResultadosDivisa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        resultadoDivisa.setBackground(new java.awt.Color(0, 204, 102));
        resultadoDivisa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        resultadoDivisa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelResultadosDivisa.add(resultadoDivisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 560, 80));

        btnOtraConversion.setText("Hacer otra conversión");
        btnOtraConversion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOtraConversion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOtraConversionMouseClicked(evt);
            }
        });
        panelResultadosDivisa.add(btnOtraConversion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, -1, -1));

        infoConversionUno.setBackground(new java.awt.Color(153, 153, 0));
        infoConversionUno.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        infoConversionUno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoConversionUno.setToolTipText("");
        panelResultadosDivisa.add(infoConversionUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 580, 40));

        infoConversionDos.setBackground(new java.awt.Color(0, 153, 204));
        infoConversionDos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        infoConversionDos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoConversionDos.setToolTipText("");
        panelResultadosDivisa.add(infoConversionDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 580, 40));

        ventanaIngresoDivisa.add(panelResultadosDivisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 580, 430));

        getContentPane().add(ventanaIngresoDivisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 630, 470));

        FondoPrincipal.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                FondoPrincipalMouseDragged(evt);
            }
        });
        FondoPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FondoPrincipalMousePressed(evt);
            }
        });
        getContentPane().add(FondoPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 470));

        setSize(new java.awt.Dimension(866, 470));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void FondoPrincipalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FondoPrincipalMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_FondoPrincipalMousePressed

    private void FondoPrincipalMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FondoPrincipalMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_FondoPrincipalMouseDragged

    private void campoIngresoDivisaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoIngresoDivisaKeyTyped
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9') && (car != '.')) {
            evt.consume();
        }
    }//GEN-LAST:event_campoIngresoDivisaKeyTyped

    private void btnConversionMonedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConversionMonedaMouseClicked
        ocultarVentanaBienvenida();
        mostrarVentanaIngresoDivisa();
        mostrarPanelValorDivisa();
        System.out.println(panelValorDivisa.getWidth());
        System.out.println(panelValorDivisa.getHeight());
    }//GEN-LAST:event_btnConversionMonedaMouseClicked

    private void btnConversionTemperaturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConversionTemperaturaMouseClicked

    }//GEN-LAST:event_btnConversionTemperaturaMouseClicked

    private void campoIngresoDivisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoIngresoDivisaKeyReleased
        String valorDivisa = campoIngresoDivisa.getText();
        if (RegexNumerosDecimales.esValorDecimal(valorDivisa)) {
            btnIngresoDivisa.setEnabled(true);
        } else {
            btnIngresoDivisa.setEnabled(false);
        }
    }//GEN-LAST:event_campoIngresoDivisaKeyReleased

    private void btnIngresoDivisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresoDivisaMouseClicked
        valorDivisa = campoIngresoDivisa.getText();
        if (esMayorQueCero(valorDivisa)) {
            ocultarPanelValorDivisa();
            mostrarPanelSeleccionDivisa();
        } else {
            JOptionPane.showMessageDialog(null, "El valor ingresado no puede ser igual a 0.");
        }

    }//GEN-LAST:event_btnIngresoDivisaMouseClicked

    private void btnBienvenidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBienvenidaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBienvenidaMouseClicked

    private void btnSeleccionDivisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeleccionDivisaMouseClicked
        ocultarPanelSeleccionDivisa();
        try {
            double tasaCambio;
            double valorUsuarioToDouble = Double.valueOf(valorDivisa);
            valorSeleccionTipoDivisa = String.valueOf(campoSeleccionDivisa.getSelectedItem());
            TestTres.esNumerico(Double.valueOf(valorUsuarioToDouble));
            tasaCambio = pesoMexicano.getTasaCambioDolarAmericanoApi();
            resultadoConversion = pesoMexicano.conversionDivisa(tasaCambio, valorUsuarioToDouble, valorSeleccionTipoDivisa);
            mostrarPanelResultadosDivisa();
            mostrarResultadosDivisa(valorUsuarioToDouble);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                    null,
                    "El valor ingresado no es un número entero o decimal",
                    "Error al recibir los datos.",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnSeleccionDivisaMouseClicked

    private void btnOtraConversionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOtraConversionMouseClicked
        reestablecerValoresDivisa();
        ocultarPanelResultadosDivisa();
        mostrarPanelValorDivisa();
    }//GEN-LAST:event_btnOtraConversionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
            * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Conversor().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoPrincipal;
    private javax.swing.JLabel btnBienvenida;
    private javax.swing.JLabel btnCerrarVentana;
    private javax.swing.JLabel btnConversionMoneda;
    private javax.swing.JLabel btnConversionTemperatura;
    private javax.swing.JButton btnIngresoDivisa;
    private javax.swing.JLabel btnMinimizarVentana;
    private javax.swing.JLabel btnOtraConversion;
    private javax.swing.JLabel btnSeleccionDivisa;
    private javax.swing.JTextField campoIngresoDivisa;
    private javax.swing.JComboBox<String> campoSeleccionDivisa;
    private javax.swing.JLabel infoConversionDos;
    private javax.swing.JLabel infoConversionUno;
    private javax.swing.JLabel instruccionCampoIngresoDivisa;
    private javax.swing.JLabel instruccionSeleccionDivisa;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel menuConversiones;
    private javax.swing.JLabel nombreDesarrollador;
    private javax.swing.JPanel panelResultadosDivisa;
    private javax.swing.JPanel panelSeleccionDivisa;
    private javax.swing.JPanel panelValorDivisa;
    private javax.swing.JLabel resultadoDivisa;
    private javax.swing.JLabel tituloBienvenida;
    private javax.swing.JPanel ventanaBienvenida;
    private javax.swing.JPanel ventanaIngresoDivisa;
    // End of variables declaration//GEN-END:variables
    class BannerConversor extends JLabel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/Imagenes/bannerConversor.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }

    class FondoPanelMenu extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/Imagenes/FondoMenu.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }

    class FondoBienvenida extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/Imagenes/challengeImage.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }

    class FondoPanelesPequenos extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/Imagenes/FondoPanelCurrency.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
}
